version: "3"

services:
  database:
    image: mysql
    container_name: jjyu1db
    volumes:
      - ~/docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=jjyudb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3306:3306
  web:
    image: jjyu1dj:v1
    build: .
    container_name: jjyu1dj
    command:
      - python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/jjyu1dj
    expose:
      - "8000"