# Generated by Django 4.1.4 on 2022-12-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('deliveries', '0001_initial'),
        ('shop_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_users.shopuser')),
            ],
            options={
                'db_table': 'shop_order',
            },
        ),
    ]
